#!/bin/bash

set -euo pipefail

BUILD_STEP_STATUS="pending"

echo 'Fetching build job status from env vars'

if [ ${BUILDKITE_COMMAND_EXIT_STATUS} == 0 ]
then
  if [ ${BUILD_SUCCESS} == "true" ]
  then
    BUILD_STEP_STATUS="success"
  else
    BUILD_STEP_STATUS="pending"
  fi
else
  BUILD_STEP_STATUS="failure"
fi

payload=$(cat <<EOF
{ \
  "state": "${BUILD_STEP_STATUS}", \
  "target_url": "${BUILDKITE_BUILD_URL}", \
  "description": "Build status from buildkite", \
  "context": "buildkite/${BUILDKITE_PIPELINE_SLUG}" \
}
EOF
)

echo 'Payload for github status'
echo ${payload}

echo 'Posting build status...'

curl -v -u praveensastry:${GIT_ACCESS_TOKEN} https://api.github.com/repos/${GIT_ORG_NAME}/${GIT_REPO_NAME}/statuses/${GIT_REF_SPEC} \
-H "Content-Type: application/json" \
-d "$payload"

echo 'Build status posted successfully'
