#!/bin/bash

set -euo pipefail

echo '--- parsing build job status'

if [ ${BUILDKITE_COMMAND_EXIT_STATUS} == 0 ]
then
  if [ ${BUILDKITE_PLUGIN_GITHUB_STATUS_STATE} == "success" ]
  then
    BUILD_STEP_STATUS="success"
  else
    BUILD_STEP_STATUS="pending"
  fi
else
  BUILD_STEP_STATUS="failure"
fi

payload=$(cat <<EOF
{ \
  "state": "${BUILD_STEP_STATUS}", \
  "target_url": "${BUILDKITE_BUILD_URL}", \
  "description": "Build status from buildkite", \
  "context": "buildkite/${BUILDKITE_PIPELINE_SLUG}" \
}
EOF
)

echo '--- payload for github status'
echo ${payload}

echo '--- posting build status...'

curl -v -u praveensastry:${GIT_ACCESS_TOKEN} https://api.github.com/repos/${GIT_ORG_NAME}/${GIT_REPO_NAME}/statuses/${GIT_REF_SPEC} \
-H "Content-Type: application/json" \
-d "$payload"

echo '--- build status posted successfully'
